# @package _global_
defaults:
 - _self_

target: Infarction
low_data_splits: ['']

# num of features
num_cat: 26
num_con: 49

# pretrain imaging
data_train_imaging: cardiac_train_paths_imaging.pt
data_val_imaging: cardiac_val_paths_imaging.pt
# pretrain tabular
data_train_tabular: cardiac_features_train_imputed_noOH_tabular_imaging_reordered.csv
data_val_tabular: cardiac_features_val_imputed_noOH_tabular_imaging_reordered.csv

field_lengths_tabular: tabular_lengths_reordered.pt

# pretrain labels
labels_train: cardiac_labels_Infarction_train.pt
labels_val: cardiac_labels_Infarction_val.pt


# finetune tabular and labels
data_train_eval_tabular: cardiac_features_train_imputed_noOH_tabular_imaging_Infarction_balanced_reordered.csv
data_train_eval_imaging: cardiac_train_paths_imaging_Infarction_balanced.pt
labels_train_eval_imaging: cardiac_labels_Infarction_train_balanced.pt
labels_train_eval_tabular: cardiac_labels_Infarction_train_balanced.pt

# data_train_eval_tabular: cardiac_features_train_imputed_noOH_tabular_imaging_reordered.csv
# data_train_eval_imaging: cardiac_train_paths_imaging.pt
# labels_train_eval_imaging: cardiac_labels_Infarction_train.pt
# labels_train_eval_tabular: cardiac_labels_Infarction_train.pt

data_val_eval_tabular: cardiac_features_val_imputed_noOH_tabular_imaging_reordered.csv
data_val_eval_imaging: cardiac_val_paths_imaging.pt
labels_val_eval_tabular: cardiac_labels_Infarction_val.pt
labels_val_eval_imaging: cardiac_labels_Infarction_val.pt

data_test_eval_tabular: cardiac_features_test_imputed_noOH_tabular_imaging_reordered.csv
data_test_eval_imaging: cardiac_test_paths_imaging.pt
labels_test_eval_tabular: cardiac_labels_Infarction_test.pt
labels_test_eval_imaging: cardiac_labels_Infarction_test.pt


# finetune imaging and labels
# data_train_eval_imaging: cardiac_train_paths_imaging_Infarction_balanced.pt
# labels_train_eval_imaging: cardiac_labels_Infarction_train_balanced.pt

# data_val_eval_imaging: cardiac_val_paths_imaging_Infarction_balanced.pt
# labels_val_eval_imaging: cardiac_labels_Infarction_val_balanced.pt

# data_test_eval_imaging: cardiac_test_paths_imaging.pt
# labels_test_eval_imaging: cardiac_labels_Infarction_test.pt