_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 48
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 48
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.11
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
