# @package _global_
defaults:
  - _self_

model: resnet50
# biobank
# lr: 3.e-3
# img_size: 128
# embedding_dim: 2048

# lr_imaging: 3.e-3
# lr_tabular: 3.e-4

# DVM
# lr: 1.e-4
img_size: 128
embedding_dim: 2048

lr_imaging: 3.e-3
lr_tabular: 3.e-4